import React, { useEffect, useState } from 'react';
import api from '../api/axios';
import { MOCK_APPOINTMENTS, MOCK_PATIENTS } from '../data/mockHospitalData';
import { useAuth } from '../context/AuthContext';
import './CareWorkspace.css';

const roleContent = {
  receptionist: { title: 'Front desk workspace', subtitle: 'Register patients, schedule visits, and manage the queue.', cards: [['Patient registration', 'Create and update patient records', 'patients'], ['Appointment scheduling', 'Book and reschedule visits', 'appointments'], ['Queue management', 'Track arrivals and waiting patients', 'queue']] },
  nurse: { title: 'Nursing workspace', subtitle: 'Record vitals, manage beds, and follow inpatient medication schedules.', cards: [['Vitals recording', 'Capture observations and notes', 'vitals'], ['Bed assignment', 'Monitor available wards and beds', 'beds'], ['Medication schedules', 'Review inpatient medication rounds', 'medication_schedules']] },
  pharmacist: { title: 'Pharmacy workspace', subtitle: 'Fill prescriptions and keep medicine inventory accurate.', cards: [['Prescription queue', 'Review and dispense ordered medicines', 'prescriptions'], ['Inventory tracking', 'Monitor stock and reorder levels', 'inventory'], ['Sales billing', 'Record pharmacy payments', 'billing']] },
  lab_technician: { title: 'Laboratory workspace', subtitle: 'Process test orders and publish reliable diagnostic results.', cards: [['Test orders', 'Receive and prioritize requests', 'lab_orders'], ['Results entry', 'Add findings to patient records', 'lab_results'], ['Diagnostic reports', 'Upload reports for clinicians', 'lab_results']] },
  billing: { title: 'Billing workspace', subtitle: 'Prepare invoices, process payments, and manage insurance claims.', cards: [['Invoice generation', 'Create final patient invoices', 'billing'], ['Payment processing', 'Record and reconcile payments', 'billing'], ['Insurance claims', 'Track claim submissions and status', 'insurance']] },
  doctor: { title: 'Clinical workspace', subtitle: 'Review patient history, create EMR notes, prescribe, and order labs.', cards: [['Patient history', 'Review diagnoses, notes, and lab results', 'records'], ['Digital prescriptions', 'Create and track medication orders', 'prescriptions'], ['Lab orders', 'Request tests and follow results', 'lab_orders']] },
};

export default function CareWorkspace() {
  const { user } = useAuth();
  const [summary, setSummary] = useState(null);
  const content = roleContent[user?.role] || roleContent.doctor;
  useEffect(() => { api.get('/workflow/summary').then((response) => setSummary(response.data.metrics)).catch(() => setSummary(null)); }, []);
  const metrics = summary || { patients: MOCK_PATIENTS.length, appointments: MOCK_APPOINTMENTS.length, pendingLabs: 4, pendingPrescriptions: 7, availableBeds: 12, unpaidBills: 6 };
  const metricCards = user?.role === 'nurse' ? [['Patients today', metrics.patients], ['Available beds', metrics.availableBeds], ['Medication rounds', 9]] : user?.role === 'lab_technician' ? [['Pending tests', metrics.pendingLabs], ['Reports today', 12], ['Urgent orders', 3]] : user?.role === 'pharmacist' ? [['Pending prescriptions', metrics.pendingPrescriptions], ['Low stock items', 4], ['Today sales', '$2,840']] : user?.role === 'billing' ? [['Unpaid bills', metrics.unpaidBills], ['Claims pending', 8], ['Collected today', '$12,480']] : [['Patients', metrics.patients], ['Appointments', metrics.appointments], ['Tasks today', 14]];
  return <div className="workspace-page"><div className="page-header"><div><h1 className="page-title">{content.title}</h1><p className="page-subtitle">{content.subtitle}</p></div><span className="workspace-role">{user?.role?.replace('_', ' ')}</span></div><div className="workspace-metrics">{metricCards.map(([label, value]) => <div className="card workspace-metric" key={label}><span>{label}</span><strong>{value}</strong><small>Mock live data</small></div>)}</div><div className="workspace-grid">{content.cards.map(([title, description, permission], index) => <button className="card workspace-module" key={permission + title} onClick={() => alert(`${title} is ready for API data and connected records.`)}><span className={`workspace-module-icon workspace-icon-${index + 1}`}>{index + 1}</span><span><strong>{title}</strong><small>{description}</small></span><b>›</b></button>)}</div><section className="card workspace-table"><div className="panel-heading"><div><h2 className="section-title">Today&apos;s activity</h2><span className="section-meta">Operational mock feed</span></div></div><div className="workspace-activity">{MOCK_APPOINTMENTS.slice(0, 4).map((appointment) => <div className="workspace-activity-row" key={appointment.id}><span className="activity-time">{appointment.time}</span><span><strong>{appointment.patient}</strong><small>{appointment.specialty} · {appointment.status}</small></span><span className="badge badge-info">{appointment.room}</span></div>)}</div></section></div>;
}
