import React from 'react';
import { useAuth } from '../context/AuthContext';
import { MOCK_APPOINTMENTS, MOCK_PATIENTS } from '../data/mockHospitalData';
import './PatientPortal.css';

export default function PatientPortal() {
  const { user } = useAuth();
  const patient = MOCK_PATIENTS.find((item) => item.email === user?.email) || MOCK_PATIENTS[0];
  const appointments = MOCK_APPOINTMENTS.filter((item) => item.patientId === patient.id);
  return <div className="portal-page"><div className="page-header"><div><h1 className="page-title">My health portal</h1><p className="page-subtitle">Your appointments, medical history, lab results, and bills in one place.</p></div></div><div className="portal-welcome card"><span className="patient-avatar patient-avatar-large">{patient.initials}</span><div><span className="portal-eyebrow">Welcome back</span><h2>{patient.name}</h2><p>{patient.id} · {patient.doctor}</p></div></div><div className="portal-grid"><section className="card portal-section"><div className="panel-heading"><div><h2 className="section-title">Upcoming appointments</h2><span className="section-meta">Your scheduled visits</span></div></div>{appointments.map((appointment) => <div className="portal-row" key={appointment.id}><div><strong>{appointment.date} at {appointment.time}</strong><small>{appointment.doctor} · {appointment.specialty}</small></div><span className="badge badge-success">{appointment.status}</span></div>)}{appointments.length === 0 && <p className="portal-empty">No upcoming appointments.</p>}</section><section className="card portal-section"><div className="panel-heading"><div><h2 className="section-title">Medical history</h2><span className="section-meta">Recent clinical documents</span></div></div><div className="portal-row"><div><strong>Hypertension follow-up</strong><small>Dr. Maya Patel · Sep 18, 2026</small></div><button className="btn btn-ghost btn-sm">View</button></div><div className="portal-row"><div><strong>Blood panel results</strong><small>Laboratory · Sep 18, 2026</small></div><button className="btn btn-ghost btn-sm">View</button></div></section><section className="card portal-section"><div className="panel-heading"><div><h2 className="section-title">Bills and lab results</h2><span className="section-meta">Secure downloads</span></div></div><div className="portal-row"><div><strong>Invoice INV-2026-1042</strong><small>$145.00 · Due Oct 2, 2026</small></div><button className="btn btn-secondary btn-sm" onClick={() => alert('Bill download will be connected to the billing API.')}>Download</button></div><div className="portal-row"><div><strong>Complete blood count</strong><small>Result available · Sep 18, 2026</small></div><button className="btn btn-secondary btn-sm">Download</button></div></section></div></div>;
}
